# Generated by Django 3.2.3 on 2021-05-14 04:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('2329054d-2be4-4040-b9fc-f210ae861bcf'), editable=False, primary_key=True, serialize=False),
        ),
    ]
