# Generated by Django 3.2.6 on 2021-08-03 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210515_0658'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='Answer',
            new_name='answer',
        ),
    ]
