# Generated by Django 3.2.3 on 2021-05-14 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210514_1728'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ('-created_at', '-updated_at'), 'verbose_name': 'Answere', 'verbose_name_plural': 'Answeres'},
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='Answare',
            new_name='Answer',
        ),
    ]
